using Allscripts.ePrescribe.Common;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace Allscripts.ePrescribe.Test.Common.ExtensionMethodTests
{
    [TestClass]
    public class SecuredStringTests
    {
        [TestMethod]
        public void should_return_encoded_string_if_the_input_value_is_script()
        {
            //Arrange
            string parameterValue = "<script>alert(Hi)</script>";

            //Act
            string result = parameterValue.ToHTMLEncode();

            //Assert
            Assert.AreEqual(result, "&lt;script&gt;alert(Hi)&lt;/script&gt;");
        }

        [TestMethod]
        public void should_return_null_if_the_input_value_is_null()
        {
            //Arrange
            string parameterValue = null;

            //Act
            string result = parameterValue.ToHTMLEncode();

            //Assert
            Assert.AreEqual(result, null);
        }

        [TestMethod]
        public void should_return_special_character_if_the_input_value_is_special_character()
        {
            //Arrange
            string parameterValue = "**&&^%$#";

            //Act
            string result = parameterValue.ToHTMLEncode();

            //Assert
            Assert.AreEqual(result, "**&amp;&amp;^%$#");
        }

        [TestMethod]
        public void should_return_empty_if_the_input_value_is_empty()
        {
            //Arrange
            string parameterValue = string.Empty;

            //Act
            string result = parameterValue.ToHTMLEncode();

            //Assert
            Assert.AreEqual(result, "");
        }

        [TestMethod]
        public void should_return_string_if_the_input_is_url()
        {
            //Arrange
            string parameterValue = "https://eprescribeqa.allscripts.com/Login.aspx";

            //Act
            string result = parameterValue.ToUrlEncode();

            //Assert
            Assert.AreEqual(result, "https%3A%2F%2Feprescribeqa.allscripts.com%2FLogin.aspx");
        }

        [TestMethod]
        public void should_return_null_if_the_input_is_null()
        {
            //Arrange
            string parameterValue = null;

            //Act
            string result = parameterValue.ToUrlEncode();

            //Assert
            Assert.AreEqual(result, null);
        }

        [TestMethod]
        public void should_return_null_if_the_input_is_empty()
        {
            //Arrange
            string parameterValue = string.Empty;

            //Act
            string result = parameterValue.ToUrlEncode();

            //Assert
            Assert.AreEqual(result, "");
        }
        [TestMethod]
        public void should_return_empty_value_if_the_input_value_is_empty()
        {
            //Arrange
            string parameterValue = string.Empty;

            //Act
            string result = parameterValue.ToXmlEncode();

            //Assert
            Assert.AreEqual(result, "");
        }
        [TestMethod]
        public void should_return_null_if_the_input_value_string_is_null()
        {
            //Arrange
            string parameterValue = null;

            //Act
            string result = parameterValue.ToXmlEncode();

            //Assert
            Assert.AreEqual(result, null);
        }
        [TestMethod]
        public void should_return_with_special_characters_if_the_input_value_is_xml()
        {
            //Arrange
            string parameterValue = "<? xml version = 1.0 ?>< user - profile >< user - guid > 5db577e8 - 0081 - 4cf6 - 866f - 0483f21392e3 </ user - guid >< user - name > adm_INTAutoSSOProv </ user - name >< dea - status > Expired </ dea - status >< message > Multiple AuthenticatedShieldUsers found.</ message ></ user - profile >";

            //Act
            string result = parameterValue.ToXmlEncode();

            //Assert
            Assert.AreEqual(result, "&lt;? xml version = 1.0 ?&gt;&lt; user - profile &gt;&lt; user - guid &gt; 5db577e8 - 0081 - 4cf6 - 866f - 0483f21392e3 &lt;/ user - guid &gt;&lt; user - name &gt; adm_INTAutoSSOProv &lt;/ user - name &gt;&lt; dea - status &gt; Expired &lt;/ dea - status &gt;&lt; message &gt; Multiple AuthenticatedShieldUsers found.&lt;/ message &gt;&lt;/ user - profile &gt;");
        }

        [TestMethod]
        public void should_return_Encoded_xml_for_DrugHistory()
        {
            //Arrange
            string sampleXml = "<xml><RXHUB_RESP_TIME>1.3415398</RXHUB_RESP_TIME><TRANS_TYPE>RXHRES</TRANS_TYPE><APPROVED>Y</APPROVED><ACCT_ID>00000000000002555994</ACCT_ID><REF_NUM>23037628654615486282791</REF_NUM><FREE_TEXT /><PRSCRBR_NO /><PRSCRBR_NO_QUAL /><PRSCRBR_LAST_NM>Ethan</PRSCRBR_LAST_NM><PRSCRBR_FIRST_NM>OBrien</PRSCRBR_FIRST_NM><PRSCRBR_MID_NM /><PRSCRBR_SUFFIX /><PRSCRBR_PREFIX /><PRSCRBR_DEA_NO /><PRSCRBR_NPI>1033434477</PRSCRBR_NPI><CLINIC_NM>Duke</CLINIC_NM><CLINIC_ADDR1>123 st</CLINIC_ADDR1><CLINIC_CITY>Raleigh</CLINIC_CITY><CLINIC_STATE>NC</CLINIC_STATE><CLINIC_ZIP>27613</CLINIC_ZIP><CLINIC_ADDR2 /><CLINIC_PHONE /><CLINIC_PHONE_QUAL /><AUTH_PRSCRBR_LAST_NM /><AUTH_PRSCRBR_FIRST_NM /><AUTH_PRSCRBR_MID_NM /><AUTH_PRSCRBR_SUFFIX /><AUTH_PRSCRBR_PREFIX /><PAT_REL_CD>1</PAT_REL_CD><PAT_DOB>1957-07-31T00:00:00</PAT_DOB><PAT_LAST_NM>John</PAT_LAST_NM><PAT_FIRST_NM>Boeing</PAT_FIRST_NM><PAT_MID_NM /><PAT_SUFFIX /><PAT_PREFIX /><PAT_GENDER>F</PAT_GENDER><PAT_SSN /><PAT_ID>791e3b84-0b7e-4c1d-b6d9-addb24577e31</PAT_ID><PAT_ADDR1>1857 85th Str</PAT_ADDR1><PAT_CITY>Brooklyn</PAT_CITY><PAT_STATE>NY</PAT_STATE><PAT_ZIP>11214</PAT_ZIP><PAT_ADDR2 /><PAT_PHONE /><PAT_PHONE_QUAL /><PAT_CONSENT>Y</PAT_CONSENT><PAT_PBM_ID>ACUNYEPP ACUNYEPPA      ACUNYEPPA101   112104852</PAT_PBM_ID><PAT_PBM_UNIQUE_ID>ACUNYEPP ACUNYEPPA      ACUNYEPPA101   112104852</PAT_PBM_UNIQUE_ID><PBM_RXHUB_ID>P00000000020123</PBM_RXHUB_ID><INFO_SRC_ID>P00000000020123</INFO_SRC_ID><INFO_SRC_NETWORK /><TEST_INDICATOR /><PAYER_ID>P00000000020123</PAYER_ID><PBM_NM /><PBM_ORG_ID /><CARD_HLDR_ID>112104852</CARD_HLDR_ID><CARD_HLDR_NM>Ethan</CARD_HLDR_NM><CARD_HLDR_GRP_NUM /><CARD_HLDR_LAST_NM>Ethan</CARD_HLDR_LAST_NM><CARD_HLDR_FIRST_NM>Ethan</CARD_HLDR_FIRST_NM><CARD_HLDR_MID_NM /><CARD_HLDR_SUFFIX /><CARD_HLDR_PREFIX /><PartnerMsgID>23037628654615486282791</PartnerMsgID><MsgID>791e3b84-0b7e-4c1d-b6d9-addb24577e31</MsgID><MAI_PAT_DESC /><MAI_PAT_IND /><MAI_VER /><DRU_START_DT>2017-04-14T00:00:00</DRU_START_DT><DRU_END_DT>2017-10-11T00:00:00</DRU_END_DT><DRUS>    <DRU>      <RX_STAT>D</RX_STAT>      <DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC>      <DRUG_NO>61958220101</DRUG_NO>      <DRUG_DOSAGE_FORM_SRC />      <DRUG_FORM />      <DRUG_STR />      <DRUG_ID />      <DRUG_ID_CD />      <DRUG_DOSAGE_FORM_CD />      <DRUG_STR_SRC />      <DRUG_STR_CD />      <DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED>      <ITEM_NO_QLF>N</ITEM_NO_QLF>      <UNIT_QTY>28</UNIT_QTY>      <UNIT_QTY_FULL>28</UNIT_QTY_FULL>      <UNIT_QTY_QLFR />      <ORIG_QTY />      <ORIG_QTY_QLFR />      <QTY_RECEIVED>28</QTY_RECEIVED>      <POTENCY_SRC_CD_LIST />      <QTY_RECEIVED_QLFR />      <POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD>      <REMAIN_QTY />      <REMAIN_QTY_QLFR />      <SIG1 />      <SIG2 />      <LAST_FILL>2017-09-06T00:00:00</LAST_FILL>      <DAYS_SUPPLY>28</DAYS_SUPPLY>      <ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT>      <EXP_DT />      <EFFCTV_DT />      <PERIOD_END />      <SUBST_CD />      <REFILL_CD />      <REFILLS />      <ICD9_PRI />      <ICD9PRIMARYCODE2 />      <ICD9_SEC />      <ICD9SECONDARYCODE2 />      <ICD10PRIMARY />      <ICD10PRIMARYCODE2 />      <ICD10SECONDARY />      <ICD10SECONDARYCODE2 />      <PRESCRIBER_ORDER_NO />      <PA_NO />      <PRESCRIBER_ORDER_NO_CODE />      <COMMENTS />      <MAI_VER />      <MAI_RX_DESC />      <MAI_RX_DAYS_LATE />      <MAI_RX_IND />      <MAI_FILL_DESC />      <MAI_FILL_DAYS_LATE />      <MAI_FILL_IND />      <RX_FILL_ID />      <PRIOR_AUTH_STATUS />      <SRC_DESC_QUAL />      <SRC_DESC />      <SRC_REF_NBR />      <SRC_REF_NBR_QUAL />      <SRC_PHARMACY_RX_NBR />      <SRC_FILL_NBR />      <DRUG_USE_EVALS>        <DUE>          <REASON />          <PRO_SC />          <RSLT_SC />          <COAGENT />          <COAGENT_CD />          <CLIN_SIGNIFICANCE_CD />          <ACK_REASON />        </DUE>      </DRUG_USE_EVALS>      <PROVIDER>        <PROVIDER_NUCC_SPECIALTY_CD />        <LASTNAME />        <FIRSTNAME />        <PROVIDER_MID_NM />        <PROVIDER_SUFFIX />        <PROVIDER_PREFIX />        <PRACTICENAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PROVIDERID />        <DEA />        <PHONE />        <FAX />        <EMAIL />      </PROVIDER>      <PHARMACY>        <NCPDP />        <PHARMACY_SPECIALTY_QUAL />        <PHARMACY_SPECIALTY_CD />        <PHARMACISTLASTNAME />        <PHARMACISTFIRSTNAME />        <NAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PHONE />        <FAX />        <EMAIL />      </PHARMACY>    </DRU>    <DRU>      <RX_STAT>D</RX_STAT>      <DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC>      <DRUG_NO>61958220101</DRUG_NO>      <DRUG_DOSAGE_FORM_SRC />      <DRUG_FORM />      <DRUG_STR />      <DRUG_ID />      <DRUG_ID_CD />      <DRUG_DOSAGE_FORM_CD />      <DRUG_STR_SRC />      <DRUG_STR_CD />      <DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED>      <ITEM_NO_QLF>N</ITEM_NO_QLF>      <UNIT_QTY>28</UNIT_QTY>      <UNIT_QTY_FULL>28</UNIT_QTY_FULL>      <UNIT_QTY_QLFR />      <ORIG_QTY />      <ORIG_QTY_QLFR />      <QTY_RECEIVED>28</QTY_RECEIVED>      <POTENCY_SRC_CD_LIST />      <QTY_RECEIVED_QLFR />      <POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD>      <REMAIN_QTY />      <REMAIN_QTY_QLFR />      <SIG1 />      <SIG2 />      <LAST_FILL>2017-08-11T00:00:00</LAST_FILL>      <DAYS_SUPPLY>28</DAYS_SUPPLY>      <ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT>      <EXP_DT />      <EFFCTV_DT />      <PERIOD_END />      <SUBST_CD />      <REFILL_CD />      <REFILLS />      <ICD9_PRI />      <ICD9PRIMARYCODE2 />      <ICD9_SEC />      <ICD9SECONDARYCODE2 />      <ICD10PRIMARY />      <ICD10PRIMARYCODE2 />      <ICD10SECONDARY />      <ICD10SECONDARYCODE2 />      <PRESCRIBER_ORDER_NO />      <PA_NO />      <PRESCRIBER_ORDER_NO_CODE />      <COMMENTS />      <MAI_VER />      <MAI_RX_DESC />      <MAI_RX_DAYS_LATE />      <MAI_RX_IND />      <MAI_FILL_DESC />      <MAI_FILL_DAYS_LATE />      <MAI_FILL_IND />      <RX_FILL_ID />      <PRIOR_AUTH_STATUS />      <SRC_DESC_QUAL />      <SRC_DESC />      <SRC_REF_NBR />      <SRC_REF_NBR_QUAL />      <SRC_PHARMACY_RX_NBR />      <SRC_FILL_NBR />      <DRUG_USE_EVALS>        <DUE>          <REASON />          <PRO_SC />          <RSLT_SC />          <COAGENT />          <COAGENT_CD />          <CLIN_SIGNIFICANCE_CD />          <ACK_REASON />        </DUE>      </DRUG_USE_EVALS>      <PROVIDER>        <PROVIDER_NUCC_SPECIALTY_CD />        <LASTNAME />        <FIRSTNAME />        <PROVIDER_MID_NM />        <PROVIDER_SUFFIX />        <PROVIDER_PREFIX />        <PRACTICENAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PROVIDERID />        <DEA />        <PHONE />        <FAX />        <EMAIL />      </PROVIDER>      <PHARMACY>        <NCPDP />        <PHARMACY_SPECIALTY_QUAL />        <PHARMACY_SPECIALTY_CD />        <PHARMACISTLASTNAME />        <PHARMACISTFIRSTNAME />        <NAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PHONE />        <FAX />        <EMAIL />      </PHARMACY>    </DRU>    <DRU>      <RX_STAT>D</RX_STAT>      <DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC>      <DRUG_NO>61958220101</DRUG_NO>      <DRUG_DOSAGE_FORM_SRC />      <DRUG_FORM />      <DRUG_STR />      <DRUG_ID />      <DRUG_ID_CD />      <DRUG_DOSAGE_FORM_CD />      <DRUG_STR_SRC />      <DRUG_STR_CD />      <DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED>      <ITEM_NO_QLF>N</ITEM_NO_QLF>      <UNIT_QTY>28</UNIT_QTY>      <UNIT_QTY_FULL>28</UNIT_QTY_FULL>      <UNIT_QTY_QLFR />      <ORIG_QTY />      <ORIG_QTY_QLFR />      <QTY_RECEIVED>28</QTY_RECEIVED>      <POTENCY_SRC_CD_LIST />      <QTY_RECEIVED_QLFR />      <POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD>      <REMAIN_QTY />      <REMAIN_QTY_QLFR />      <SIG1 />      <SIG2 />      <LAST_FILL>2017-07-13T00:00:00</LAST_FILL>      <DAYS_SUPPLY>28</DAYS_SUPPLY>      <ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT>      <EXP_DT />      <EFFCTV_DT />      <PERIOD_END />      <SUBST_CD />      <REFILL_CD />      <REFILLS />      <ICD9_PRI />      <ICD9PRIMARYCODE2 />      <ICD9_SEC />      <ICD9SECONDARYCODE2 />      <ICD10PRIMARY />      <ICD10PRIMARYCODE2 />      <ICD10SECONDARY />      <ICD10SECONDARYCODE2 />      <PRESCRIBER_ORDER_NO />      <PA_NO />      <PRESCRIBER_ORDER_NO_CODE />      <COMMENTS />      <MAI_VER />      <MAI_RX_DESC />      <MAI_RX_DAYS_LATE />      <MAI_RX_IND />      <MAI_FILL_DESC />      <MAI_FILL_DAYS_LATE />      <MAI_FILL_IND />      <RX_FILL_ID />      <PRIOR_AUTH_STATUS />      <SRC_DESC_QUAL />      <SRC_DESC />      <SRC_REF_NBR />      <SRC_REF_NBR_QUAL />      <SRC_PHARMACY_RX_NBR />      <SRC_FILL_NBR />      <DRUG_USE_EVALS>        <DUE>          <REASON />          <PRO_SC />          <RSLT_SC />          <COAGENT />          <COAGENT_CD />          <CLIN_SIGNIFICANCE_CD />          <ACK_REASON />        </DUE>      </DRUG_USE_EVALS>      <PROVIDER>        <PROVIDER_NUCC_SPECIALTY_CD />        <LASTNAME />        <FIRSTNAME />        <PROVIDER_MID_NM />        <PROVIDER_SUFFIX />        <PROVIDER_PREFIX />        <PRACTICENAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PROVIDERID />        <DEA />        <PHONE />        <FAX />        <EMAIL />      </PROVIDER>      <PHARMACY>        <NCPDP />        <PHARMACY_SPECIALTY_QUAL />        <PHARMACY_SPECIALTY_CD />        <PHARMACISTLASTNAME />        <PHARMACISTFIRSTNAME />        <NAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PHONE />        <FAX />        <EMAIL />      </PHARMACY>    </DRU>    <DRU>      <RX_STAT>D</RX_STAT>      <DRUG_DESC>PAIN &amp; FEVER EXTRA STRENGTH 500 MGTABS</DRUG_DESC>      <DRUG_NO>00536323110</DRUG_NO>      <DRUG_DOSAGE_FORM_SRC />      <DRUG_FORM />      <DRUG_STR />      <DRUG_ID />      <DRUG_ID_CD />      <DRUG_DOSAGE_FORM_CD />      <DRUG_STR_SRC />      <DRUG_STR_CD />      <DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED>      <ITEM_NO_QLF>N</ITEM_NO_QLF>      <UNIT_QTY>100</UNIT_QTY>      <UNIT_QTY_FULL>100</UNIT_QTY_FULL>      <UNIT_QTY_QLFR />      <ORIG_QTY />      <ORIG_QTY_QLFR />      <QTY_RECEIVED>100</QTY_RECEIVED>      <POTENCY_SRC_CD_LIST />      <QTY_RECEIVED_QLFR />      <POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD>      <REMAIN_QTY />      <REMAIN_QTY_QLFR />      <SIG1 />      <SIG2 />      <LAST_FILL>2017-05-26T00:00:00</LAST_FILL>      <DAYS_SUPPLY>15</DAYS_SUPPLY>      <ISSUED_DT>2017-05-26T00:00:00</ISSUED_DT>      <EXP_DT />      <EFFCTV_DT />      <PERIOD_END />      <SUBST_CD />      <REFILL_CD />      <REFILLS />      <ICD9_PRI />      <ICD9PRIMARYCODE2 />      <ICD9_SEC />      <ICD9SECONDARYCODE2 />      <ICD10PRIMARY />      <ICD10PRIMARYCODE2 />      <ICD10SECONDARY />      <ICD10SECONDARYCODE2 />      <PRESCRIBER_ORDER_NO />      <PA_NO />      <PRESCRIBER_ORDER_NO_CODE />      <COMMENTS />      <MAI_VER />      <MAI_RX_DESC />      <MAI_RX_DAYS_LATE />      <MAI_RX_IND />      <MAI_FILL_DESC />      <MAI_FILL_DAYS_LATE />      <MAI_FILL_IND />      <RX_FILL_ID />      <PRIOR_AUTH_STATUS />      <SRC_DESC_QUAL />      <SRC_DESC />      <SRC_REF_NBR />      <SRC_REF_NBR_QUAL />      <SRC_PHARMACY_RX_NBR />      <SRC_FILL_NBR />      <DRUG_USE_EVALS>        <DUE>          <REASON />          <PRO_SC />          <RSLT_SC />          <COAGENT />          <COAGENT_CD />          <CLIN_SIGNIFICANCE_CD />          <ACK_REASON />        </DUE>      </DRUG_USE_EVALS>      <PROVIDER>        <PROVIDER_NUCC_SPECIALTY_CD />        <LASTNAME />        <FIRSTNAME />        <PROVIDER_MID_NM />        <PROVIDER_SUFFIX />        <PROVIDER_PREFIX />        <PRACTICENAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PROVIDERID />        <DEA />        <PHONE />        <FAX />        <EMAIL />      </PROVIDER>      <PHARMACY>        <NCPDP />        <PHARMACY_SPECIALTY_QUAL />        <PHARMACY_SPECIALTY_CD />        <PHARMACISTLASTNAME />        <PHARMACISTFIRSTNAME />        <NAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PHONE />        <FAX />        <EMAIL />      </PHARMACY>    </DRU>    <DRU>      <RX_STAT>D</RX_STAT>      <DRUG_DESC>IBUPROFEN 200 MG TABS</DRUG_DESC>      <DRUG_NO>00536108801</DRUG_NO>      <DRUG_DOSAGE_FORM_SRC />      <DRUG_FORM />      <DRUG_STR />      <DRUG_ID />      <DRUG_ID_CD />      <DRUG_DOSAGE_FORM_CD />      <DRUG_STR_SRC />      <DRUG_STR_CD />      <DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED>      <ITEM_NO_QLF>N</ITEM_NO_QLF>      <UNIT_QTY>60</UNIT_QTY>      <UNIT_QTY_FULL>60</UNIT_QTY_FULL>      <UNIT_QTY_QLFR />      <ORIG_QTY />      <ORIG_QTY_QLFR />      <QTY_RECEIVED>60</QTY_RECEIVED>      <POTENCY_SRC_CD_LIST />      <QTY_RECEIVED_QLFR />      <POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD>      <REMAIN_QTY />      <REMAIN_QTY_QLFR />      <SIG1 />      <SIG2 />      <LAST_FILL>2017-05-25T00:00:00</LAST_FILL>      <DAYS_SUPPLY>6</DAYS_SUPPLY>      <ISSUED_DT>2017-05-25T00:00:00</ISSUED_DT>      <EXP_DT />      <EFFCTV_DT />      <PERIOD_END />      <SUBST_CD />      <REFILL_CD />      <REFILLS />      <ICD9_PRI />      <ICD9PRIMARYCODE2 />      <ICD9_SEC />      <ICD9SECONDARYCODE2 />      <ICD10PRIMARY />      <ICD10PRIMARYCODE2 />      <ICD10SECONDARY />      <ICD10SECONDARYCODE2 />      <PRESCRIBER_ORDER_NO />      <PA_NO />      <PRESCRIBER_ORDER_NO_CODE />      <COMMENTS />      <MAI_VER />      <MAI_RX_DESC />      <MAI_RX_DAYS_LATE />      <MAI_RX_IND />      <MAI_FILL_DESC />      <MAI_FILL_DAYS_LATE />      <MAI_FILL_IND />      <RX_FILL_ID />      <PRIOR_AUTH_STATUS />      <SRC_DESC_QUAL />      <SRC_DESC />      <SRC_REF_NBR />      <SRC_REF_NBR_QUAL />      <SRC_PHARMACY_RX_NBR />      <SRC_FILL_NBR />      <DRUG_USE_EVALS>        <DUE>          <REASON />          <PRO_SC />          <RSLT_SC />          <COAGENT />          <COAGENT_CD />          <CLIN_SIGNIFICANCE_CD />          <ACK_REASON />        </DUE>      </DRUG_USE_EVALS>      <PROVIDER>        <PROVIDER_NUCC_SPECIALTY_CD />        <LASTNAME />        <FIRSTNAME />        <PROVIDER_MID_NM />        <PROVIDER_SUFFIX />        <PROVIDER_PREFIX />        <PRACTICENAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PROVIDERID />        <DEA />        <PHONE />        <FAX />        <EMAIL />      </PROVIDER>      <PHARMACY>        <NCPDP />        <PHARMACY_SPECIALTY_QUAL />        <PHARMACY_SPECIALTY_CD />        <PHARMACISTLASTNAME />        <PHARMACISTFIRSTNAME />        <NAME />        <ADDRESS1 />        <ADDRESS2 />        <CITY />        <STATE />        <ZIP />        <PHONE />        <FAX />        <EMAIL />      </PHARMACY>    </DRU>  </DRUS>  <UNIQUE_REQUEST>Y</UNIQUE_REQUEST>  <TOTAL_RECORDS>5</TOTAL_RECORDS></xml>";
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(sampleXml);
            XmlNode newNode = doc.DocumentElement;

            //Act
            XmlNode result =  newNode.XmlEncode();

            //Assert
            Assert.AreEqual(result.OuterXml, "<xml><RXHUB_RESP_TIME>1.3415398</RXHUB_RESP_TIME><TRANS_TYPE>RXHRES</TRANS_TYPE><APPROVED>Y</APPROVED><ACCT_ID>00000000000002555994</ACCT_ID><REF_NUM>23037628654615486282791</REF_NUM><FREE_TEXT></FREE_TEXT><PRSCRBR_NO></PRSCRBR_NO><PRSCRBR_NO_QUAL></PRSCRBR_NO_QUAL><PRSCRBR_LAST_NM>Ethan</PRSCRBR_LAST_NM><PRSCRBR_FIRST_NM>OBrien</PRSCRBR_FIRST_NM><PRSCRBR_MID_NM></PRSCRBR_MID_NM><PRSCRBR_SUFFIX></PRSCRBR_SUFFIX><PRSCRBR_PREFIX></PRSCRBR_PREFIX><PRSCRBR_DEA_NO></PRSCRBR_DEA_NO><PRSCRBR_NPI>1033434477</PRSCRBR_NPI><CLINIC_NM>Duke</CLINIC_NM><CLINIC_ADDR1>123 st</CLINIC_ADDR1><CLINIC_CITY>Raleigh</CLINIC_CITY><CLINIC_STATE>NC</CLINIC_STATE><CLINIC_ZIP>27613</CLINIC_ZIP><CLINIC_ADDR2></CLINIC_ADDR2><CLINIC_PHONE></CLINIC_PHONE><CLINIC_PHONE_QUAL></CLINIC_PHONE_QUAL><AUTH_PRSCRBR_LAST_NM></AUTH_PRSCRBR_LAST_NM><AUTH_PRSCRBR_FIRST_NM></AUTH_PRSCRBR_FIRST_NM><AUTH_PRSCRBR_MID_NM></AUTH_PRSCRBR_MID_NM><AUTH_PRSCRBR_SUFFIX></AUTH_PRSCRBR_SUFFIX><AUTH_PRSCRBR_PREFIX></AUTH_PRSCRBR_PREFIX><PAT_REL_CD>1</PAT_REL_CD><PAT_DOB>1957-07-31T00:00:00</PAT_DOB><PAT_LAST_NM>John</PAT_LAST_NM><PAT_FIRST_NM>Boeing</PAT_FIRST_NM><PAT_MID_NM></PAT_MID_NM><PAT_SUFFIX></PAT_SUFFIX><PAT_PREFIX></PAT_PREFIX><PAT_GENDER>F</PAT_GENDER><PAT_SSN></PAT_SSN><PAT_ID>791e3b84-0b7e-4c1d-b6d9-addb24577e31</PAT_ID><PAT_ADDR1>1857 85th Str</PAT_ADDR1><PAT_CITY>Brooklyn</PAT_CITY><PAT_STATE>NY</PAT_STATE><PAT_ZIP>11214</PAT_ZIP><PAT_ADDR2></PAT_ADDR2><PAT_PHONE></PAT_PHONE><PAT_PHONE_QUAL></PAT_PHONE_QUAL><PAT_CONSENT>Y</PAT_CONSENT><PAT_PBM_ID>ACUNYEPP ACUNYEPPA      ACUNYEPPA101   112104852</PAT_PBM_ID><PAT_PBM_UNIQUE_ID>ACUNYEPP ACUNYEPPA      ACUNYEPPA101   112104852</PAT_PBM_UNIQUE_ID><PBM_RXHUB_ID>P00000000020123</PBM_RXHUB_ID><INFO_SRC_ID>P00000000020123</INFO_SRC_ID><INFO_SRC_NETWORK></INFO_SRC_NETWORK><TEST_INDICATOR></TEST_INDICATOR><PAYER_ID>P00000000020123</PAYER_ID><PBM_NM></PBM_NM><PBM_ORG_ID></PBM_ORG_ID><CARD_HLDR_ID>112104852</CARD_HLDR_ID><CARD_HLDR_NM>Ethan</CARD_HLDR_NM><CARD_HLDR_GRP_NUM></CARD_HLDR_GRP_NUM><CARD_HLDR_LAST_NM>Ethan</CARD_HLDR_LAST_NM><CARD_HLDR_FIRST_NM>Ethan</CARD_HLDR_FIRST_NM><CARD_HLDR_MID_NM></CARD_HLDR_MID_NM><CARD_HLDR_SUFFIX></CARD_HLDR_SUFFIX><CARD_HLDR_PREFIX></CARD_HLDR_PREFIX><PartnerMsgID>23037628654615486282791</PartnerMsgID><MsgID>791e3b84-0b7e-4c1d-b6d9-addb24577e31</MsgID><MAI_PAT_DESC></MAI_PAT_DESC><MAI_PAT_IND></MAI_PAT_IND><MAI_VER></MAI_VER><DRU_START_DT>2017-04-14T00:00:00</DRU_START_DT><DRU_END_DT>2017-10-11T00:00:00</DRU_END_DT><DRUS><DRU><RX_STAT>D</RX_STAT><DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC><DRUG_NO>61958220101</DRUG_NO><DRUG_DOSAGE_FORM_SRC></DRUG_DOSAGE_FORM_SRC><DRUG_FORM></DRUG_FORM><DRUG_STR></DRUG_STR><DRUG_ID></DRUG_ID><DRUG_ID_CD></DRUG_ID_CD><DRUG_DOSAGE_FORM_CD></DRUG_DOSAGE_FORM_CD><DRUG_STR_SRC></DRUG_STR_SRC><DRUG_STR_CD></DRUG_STR_CD><DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED><ITEM_NO_QLF>N</ITEM_NO_QLF><UNIT_QTY>28</UNIT_QTY><UNIT_QTY_FULL>28</UNIT_QTY_FULL><UNIT_QTY_QLFR></UNIT_QTY_QLFR><ORIG_QTY></ORIG_QTY><ORIG_QTY_QLFR></ORIG_QTY_QLFR><QTY_RECEIVED>28</QTY_RECEIVED><POTENCY_SRC_CD_LIST></POTENCY_SRC_CD_LIST><QTY_RECEIVED_QLFR></QTY_RECEIVED_QLFR><POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD><REMAIN_QTY></REMAIN_QTY><REMAIN_QTY_QLFR></REMAIN_QTY_QLFR><SIG1></SIG1><SIG2></SIG2><LAST_FILL>2017-09-06T00:00:00</LAST_FILL><DAYS_SUPPLY>28</DAYS_SUPPLY><ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT><EXP_DT></EXP_DT><EFFCTV_DT></EFFCTV_DT><PERIOD_END></PERIOD_END><SUBST_CD></SUBST_CD><REFILL_CD></REFILL_CD><REFILLS></REFILLS><ICD9_PRI></ICD9_PRI><ICD9PRIMARYCODE2></ICD9PRIMARYCODE2><ICD9_SEC></ICD9_SEC><ICD9SECONDARYCODE2></ICD9SECONDARYCODE2><ICD10PRIMARY></ICD10PRIMARY><ICD10PRIMARYCODE2></ICD10PRIMARYCODE2><ICD10SECONDARY></ICD10SECONDARY><ICD10SECONDARYCODE2></ICD10SECONDARYCODE2><PRESCRIBER_ORDER_NO></PRESCRIBER_ORDER_NO><PA_NO></PA_NO><PRESCRIBER_ORDER_NO_CODE></PRESCRIBER_ORDER_NO_CODE><COMMENTS></COMMENTS><MAI_VER></MAI_VER><MAI_RX_DESC></MAI_RX_DESC><MAI_RX_DAYS_LATE></MAI_RX_DAYS_LATE><MAI_RX_IND></MAI_RX_IND><MAI_FILL_DESC></MAI_FILL_DESC><MAI_FILL_DAYS_LATE></MAI_FILL_DAYS_LATE><MAI_FILL_IND></MAI_FILL_IND><RX_FILL_ID></RX_FILL_ID><PRIOR_AUTH_STATUS></PRIOR_AUTH_STATUS><SRC_DESC_QUAL></SRC_DESC_QUAL><SRC_DESC></SRC_DESC><SRC_REF_NBR></SRC_REF_NBR><SRC_REF_NBR_QUAL></SRC_REF_NBR_QUAL><SRC_PHARMACY_RX_NBR></SRC_PHARMACY_RX_NBR><SRC_FILL_NBR></SRC_FILL_NBR><DRUG_USE_EVALS><DUE><REASON></REASON><PRO_SC></PRO_SC><RSLT_SC></RSLT_SC><COAGENT></COAGENT><COAGENT_CD></COAGENT_CD><CLIN_SIGNIFICANCE_CD></CLIN_SIGNIFICANCE_CD><ACK_REASON></ACK_REASON></DUE></DRUG_USE_EVALS><PROVIDER><PROVIDER_NUCC_SPECIALTY_CD></PROVIDER_NUCC_SPECIALTY_CD><LASTNAME></LASTNAME><FIRSTNAME></FIRSTNAME><PROVIDER_MID_NM></PROVIDER_MID_NM><PROVIDER_SUFFIX></PROVIDER_SUFFIX><PROVIDER_PREFIX></PROVIDER_PREFIX><PRACTICENAME></PRACTICENAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PROVIDERID></PROVIDERID><DEA></DEA><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PROVIDER><PHARMACY><NCPDP></NCPDP><PHARMACY_SPECIALTY_QUAL></PHARMACY_SPECIALTY_QUAL><PHARMACY_SPECIALTY_CD></PHARMACY_SPECIALTY_CD><PHARMACISTLASTNAME></PHARMACISTLASTNAME><PHARMACISTFIRSTNAME></PHARMACISTFIRSTNAME><NAME></NAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PHARMACY></DRU><DRU><RX_STAT>D</RX_STAT><DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC><DRUG_NO>61958220101</DRUG_NO><DRUG_DOSAGE_FORM_SRC></DRUG_DOSAGE_FORM_SRC><DRUG_FORM></DRUG_FORM><DRUG_STR></DRUG_STR><DRUG_ID></DRUG_ID><DRUG_ID_CD></DRUG_ID_CD><DRUG_DOSAGE_FORM_CD></DRUG_DOSAGE_FORM_CD><DRUG_STR_SRC></DRUG_STR_SRC><DRUG_STR_CD></DRUG_STR_CD><DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED><ITEM_NO_QLF>N</ITEM_NO_QLF><UNIT_QTY>28</UNIT_QTY><UNIT_QTY_FULL>28</UNIT_QTY_FULL><UNIT_QTY_QLFR></UNIT_QTY_QLFR><ORIG_QTY></ORIG_QTY><ORIG_QTY_QLFR></ORIG_QTY_QLFR><QTY_RECEIVED>28</QTY_RECEIVED><POTENCY_SRC_CD_LIST></POTENCY_SRC_CD_LIST><QTY_RECEIVED_QLFR></QTY_RECEIVED_QLFR><POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD><REMAIN_QTY></REMAIN_QTY><REMAIN_QTY_QLFR></REMAIN_QTY_QLFR><SIG1></SIG1><SIG2></SIG2><LAST_FILL>2017-08-11T00:00:00</LAST_FILL><DAYS_SUPPLY>28</DAYS_SUPPLY><ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT><EXP_DT></EXP_DT><EFFCTV_DT></EFFCTV_DT><PERIOD_END></PERIOD_END><SUBST_CD></SUBST_CD><REFILL_CD></REFILL_CD><REFILLS></REFILLS><ICD9_PRI></ICD9_PRI><ICD9PRIMARYCODE2></ICD9PRIMARYCODE2><ICD9_SEC></ICD9_SEC><ICD9SECONDARYCODE2></ICD9SECONDARYCODE2><ICD10PRIMARY></ICD10PRIMARY><ICD10PRIMARYCODE2></ICD10PRIMARYCODE2><ICD10SECONDARY></ICD10SECONDARY><ICD10SECONDARYCODE2></ICD10SECONDARYCODE2><PRESCRIBER_ORDER_NO></PRESCRIBER_ORDER_NO><PA_NO></PA_NO><PRESCRIBER_ORDER_NO_CODE></PRESCRIBER_ORDER_NO_CODE><COMMENTS></COMMENTS><MAI_VER></MAI_VER><MAI_RX_DESC></MAI_RX_DESC><MAI_RX_DAYS_LATE></MAI_RX_DAYS_LATE><MAI_RX_IND></MAI_RX_IND><MAI_FILL_DESC></MAI_FILL_DESC><MAI_FILL_DAYS_LATE></MAI_FILL_DAYS_LATE><MAI_FILL_IND></MAI_FILL_IND><RX_FILL_ID></RX_FILL_ID><PRIOR_AUTH_STATUS></PRIOR_AUTH_STATUS><SRC_DESC_QUAL></SRC_DESC_QUAL><SRC_DESC></SRC_DESC><SRC_REF_NBR></SRC_REF_NBR><SRC_REF_NBR_QUAL></SRC_REF_NBR_QUAL><SRC_PHARMACY_RX_NBR></SRC_PHARMACY_RX_NBR><SRC_FILL_NBR></SRC_FILL_NBR><DRUG_USE_EVALS><DUE><REASON></REASON><PRO_SC></PRO_SC><RSLT_SC></RSLT_SC><COAGENT></COAGENT><COAGENT_CD></COAGENT_CD><CLIN_SIGNIFICANCE_CD></CLIN_SIGNIFICANCE_CD><ACK_REASON></ACK_REASON></DUE></DRUG_USE_EVALS><PROVIDER><PROVIDER_NUCC_SPECIALTY_CD></PROVIDER_NUCC_SPECIALTY_CD><LASTNAME></LASTNAME><FIRSTNAME></FIRSTNAME><PROVIDER_MID_NM></PROVIDER_MID_NM><PROVIDER_SUFFIX></PROVIDER_SUFFIX><PROVIDER_PREFIX></PROVIDER_PREFIX><PRACTICENAME></PRACTICENAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PROVIDERID></PROVIDERID><DEA></DEA><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PROVIDER><PHARMACY><NCPDP></NCPDP><PHARMACY_SPECIALTY_QUAL></PHARMACY_SPECIALTY_QUAL><PHARMACY_SPECIALTY_CD></PHARMACY_SPECIALTY_CD><PHARMACISTLASTNAME></PHARMACISTLASTNAME><PHARMACISTFIRSTNAME></PHARMACISTFIRSTNAME><NAME></NAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PHARMACY></DRU><DRU><RX_STAT>D</RX_STAT><DRUG_DESC>EPCLUSA      TAB 400-100</DRUG_DESC><DRUG_NO>61958220101</DRUG_NO><DRUG_DOSAGE_FORM_SRC></DRUG_DOSAGE_FORM_SRC><DRUG_FORM></DRUG_FORM><DRUG_STR></DRUG_STR><DRUG_ID></DRUG_ID><DRUG_ID_CD></DRUG_ID_CD><DRUG_DOSAGE_FORM_CD></DRUG_DOSAGE_FORM_CD><DRUG_STR_SRC></DRUG_STR_SRC><DRUG_STR_CD></DRUG_STR_CD><DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED><ITEM_NO_QLF>N</ITEM_NO_QLF><UNIT_QTY>28</UNIT_QTY><UNIT_QTY_FULL>28</UNIT_QTY_FULL><UNIT_QTY_QLFR></UNIT_QTY_QLFR><ORIG_QTY></ORIG_QTY><ORIG_QTY_QLFR></ORIG_QTY_QLFR><QTY_RECEIVED>28</QTY_RECEIVED><POTENCY_SRC_CD_LIST></POTENCY_SRC_CD_LIST><QTY_RECEIVED_QLFR></QTY_RECEIVED_QLFR><POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD><REMAIN_QTY></REMAIN_QTY><REMAIN_QTY_QLFR></REMAIN_QTY_QLFR><SIG1></SIG1><SIG2></SIG2><LAST_FILL>2017-07-13T00:00:00</LAST_FILL><DAYS_SUPPLY>28</DAYS_SUPPLY><ISSUED_DT>2017-07-13T00:00:00</ISSUED_DT><EXP_DT></EXP_DT><EFFCTV_DT></EFFCTV_DT><PERIOD_END></PERIOD_END><SUBST_CD></SUBST_CD><REFILL_CD></REFILL_CD><REFILLS></REFILLS><ICD9_PRI></ICD9_PRI><ICD9PRIMARYCODE2></ICD9PRIMARYCODE2><ICD9_SEC></ICD9_SEC><ICD9SECONDARYCODE2></ICD9SECONDARYCODE2><ICD10PRIMARY></ICD10PRIMARY><ICD10PRIMARYCODE2></ICD10PRIMARYCODE2><ICD10SECONDARY></ICD10SECONDARY><ICD10SECONDARYCODE2></ICD10SECONDARYCODE2><PRESCRIBER_ORDER_NO></PRESCRIBER_ORDER_NO><PA_NO></PA_NO><PRESCRIBER_ORDER_NO_CODE></PRESCRIBER_ORDER_NO_CODE><COMMENTS></COMMENTS><MAI_VER></MAI_VER><MAI_RX_DESC></MAI_RX_DESC><MAI_RX_DAYS_LATE></MAI_RX_DAYS_LATE><MAI_RX_IND></MAI_RX_IND><MAI_FILL_DESC></MAI_FILL_DESC><MAI_FILL_DAYS_LATE></MAI_FILL_DAYS_LATE><MAI_FILL_IND></MAI_FILL_IND><RX_FILL_ID></RX_FILL_ID><PRIOR_AUTH_STATUS></PRIOR_AUTH_STATUS><SRC_DESC_QUAL></SRC_DESC_QUAL><SRC_DESC></SRC_DESC><SRC_REF_NBR></SRC_REF_NBR><SRC_REF_NBR_QUAL></SRC_REF_NBR_QUAL><SRC_PHARMACY_RX_NBR></SRC_PHARMACY_RX_NBR><SRC_FILL_NBR></SRC_FILL_NBR><DRUG_USE_EVALS><DUE><REASON></REASON><PRO_SC></PRO_SC><RSLT_SC></RSLT_SC><COAGENT></COAGENT><COAGENT_CD></COAGENT_CD><CLIN_SIGNIFICANCE_CD></CLIN_SIGNIFICANCE_CD><ACK_REASON></ACK_REASON></DUE></DRUG_USE_EVALS><PROVIDER><PROVIDER_NUCC_SPECIALTY_CD></PROVIDER_NUCC_SPECIALTY_CD><LASTNAME></LASTNAME><FIRSTNAME></FIRSTNAME><PROVIDER_MID_NM></PROVIDER_MID_NM><PROVIDER_SUFFIX></PROVIDER_SUFFIX><PROVIDER_PREFIX></PROVIDER_PREFIX><PRACTICENAME></PRACTICENAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PROVIDERID></PROVIDERID><DEA></DEA><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PROVIDER><PHARMACY><NCPDP></NCPDP><PHARMACY_SPECIALTY_QUAL></PHARMACY_SPECIALTY_QUAL><PHARMACY_SPECIALTY_CD></PHARMACY_SPECIALTY_CD><PHARMACISTLASTNAME></PHARMACISTLASTNAME><PHARMACISTFIRSTNAME></PHARMACISTFIRSTNAME><NAME></NAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PHARMACY></DRU><DRU><RX_STAT>D</RX_STAT><DRUG_DESC>PAIN &amp;amp; FEVER EXTRA STRENGTH 500 MGTABS</DRUG_DESC><DRUG_NO>00536323110</DRUG_NO><DRUG_DOSAGE_FORM_SRC></DRUG_DOSAGE_FORM_SRC><DRUG_FORM></DRUG_FORM><DRUG_STR></DRUG_STR><DRUG_ID></DRUG_ID><DRUG_ID_CD></DRUG_ID_CD><DRUG_DOSAGE_FORM_CD></DRUG_DOSAGE_FORM_CD><DRUG_STR_SRC></DRUG_STR_SRC><DRUG_STR_CD></DRUG_STR_CD><DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED><ITEM_NO_QLF>N</ITEM_NO_QLF><UNIT_QTY>100</UNIT_QTY><UNIT_QTY_FULL>100</UNIT_QTY_FULL><UNIT_QTY_QLFR></UNIT_QTY_QLFR><ORIG_QTY></ORIG_QTY><ORIG_QTY_QLFR></ORIG_QTY_QLFR><QTY_RECEIVED>100</QTY_RECEIVED><POTENCY_SRC_CD_LIST></POTENCY_SRC_CD_LIST><QTY_RECEIVED_QLFR></QTY_RECEIVED_QLFR><POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD><REMAIN_QTY></REMAIN_QTY><REMAIN_QTY_QLFR></REMAIN_QTY_QLFR><SIG1></SIG1><SIG2></SIG2><LAST_FILL>2017-05-26T00:00:00</LAST_FILL><DAYS_SUPPLY>15</DAYS_SUPPLY><ISSUED_DT>2017-05-26T00:00:00</ISSUED_DT><EXP_DT></EXP_DT><EFFCTV_DT></EFFCTV_DT><PERIOD_END></PERIOD_END><SUBST_CD></SUBST_CD><REFILL_CD></REFILL_CD><REFILLS></REFILLS><ICD9_PRI></ICD9_PRI><ICD9PRIMARYCODE2></ICD9PRIMARYCODE2><ICD9_SEC></ICD9_SEC><ICD9SECONDARYCODE2></ICD9SECONDARYCODE2><ICD10PRIMARY></ICD10PRIMARY><ICD10PRIMARYCODE2></ICD10PRIMARYCODE2><ICD10SECONDARY></ICD10SECONDARY><ICD10SECONDARYCODE2></ICD10SECONDARYCODE2><PRESCRIBER_ORDER_NO></PRESCRIBER_ORDER_NO><PA_NO></PA_NO><PRESCRIBER_ORDER_NO_CODE></PRESCRIBER_ORDER_NO_CODE><COMMENTS></COMMENTS><MAI_VER></MAI_VER><MAI_RX_DESC></MAI_RX_DESC><MAI_RX_DAYS_LATE></MAI_RX_DAYS_LATE><MAI_RX_IND></MAI_RX_IND><MAI_FILL_DESC></MAI_FILL_DESC><MAI_FILL_DAYS_LATE></MAI_FILL_DAYS_LATE><MAI_FILL_IND></MAI_FILL_IND><RX_FILL_ID></RX_FILL_ID><PRIOR_AUTH_STATUS></PRIOR_AUTH_STATUS><SRC_DESC_QUAL></SRC_DESC_QUAL><SRC_DESC></SRC_DESC><SRC_REF_NBR></SRC_REF_NBR><SRC_REF_NBR_QUAL></SRC_REF_NBR_QUAL><SRC_PHARMACY_RX_NBR></SRC_PHARMACY_RX_NBR><SRC_FILL_NBR></SRC_FILL_NBR><DRUG_USE_EVALS><DUE><REASON></REASON><PRO_SC></PRO_SC><RSLT_SC></RSLT_SC><COAGENT></COAGENT><COAGENT_CD></COAGENT_CD><CLIN_SIGNIFICANCE_CD></CLIN_SIGNIFICANCE_CD><ACK_REASON></ACK_REASON></DUE></DRUG_USE_EVALS><PROVIDER><PROVIDER_NUCC_SPECIALTY_CD></PROVIDER_NUCC_SPECIALTY_CD><LASTNAME></LASTNAME><FIRSTNAME></FIRSTNAME><PROVIDER_MID_NM></PROVIDER_MID_NM><PROVIDER_SUFFIX></PROVIDER_SUFFIX><PROVIDER_PREFIX></PROVIDER_PREFIX><PRACTICENAME></PRACTICENAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PROVIDERID></PROVIDERID><DEA></DEA><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PROVIDER><PHARMACY><NCPDP></NCPDP><PHARMACY_SPECIALTY_QUAL></PHARMACY_SPECIALTY_QUAL><PHARMACY_SPECIALTY_CD></PHARMACY_SPECIALTY_CD><PHARMACISTLASTNAME></PHARMACISTLASTNAME><PHARMACISTFIRSTNAME></PHARMACISTFIRSTNAME><NAME></NAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PHARMACY></DRU><DRU><RX_STAT>D</RX_STAT><DRUG_DESC>IBUPROFEN 200 MG TABS</DRUG_DESC><DRUG_NO>00536108801</DRUG_NO><DRUG_DOSAGE_FORM_SRC></DRUG_DOSAGE_FORM_SRC><DRUG_FORM></DRUG_FORM><DRUG_STR></DRUG_STR><DRUG_ID></DRUG_ID><DRUG_ID_CD></DRUG_ID_CD><DRUG_DOSAGE_FORM_CD></DRUG_DOSAGE_FORM_CD><DRUG_STR_SRC></DRUG_STR_SRC><DRUG_STR_CD></DRUG_STR_CD><DRUG_DEA_SCHED>C38046</DRUG_DEA_SCHED><ITEM_NO_QLF>N</ITEM_NO_QLF><UNIT_QTY>60</UNIT_QTY><UNIT_QTY_FULL>60</UNIT_QTY_FULL><UNIT_QTY_QLFR></UNIT_QTY_QLFR><ORIG_QTY></ORIG_QTY><ORIG_QTY_QLFR></ORIG_QTY_QLFR><QTY_RECEIVED>60</QTY_RECEIVED><POTENCY_SRC_CD_LIST></POTENCY_SRC_CD_LIST><QTY_RECEIVED_QLFR></QTY_RECEIVED_QLFR><POTENCY_UNIT_CD>C48477</POTENCY_UNIT_CD><REMAIN_QTY></REMAIN_QTY><REMAIN_QTY_QLFR></REMAIN_QTY_QLFR><SIG1></SIG1><SIG2></SIG2><LAST_FILL>2017-05-25T00:00:00</LAST_FILL><DAYS_SUPPLY>6</DAYS_SUPPLY><ISSUED_DT>2017-05-25T00:00:00</ISSUED_DT><EXP_DT></EXP_DT><EFFCTV_DT></EFFCTV_DT><PERIOD_END></PERIOD_END><SUBST_CD></SUBST_CD><REFILL_CD></REFILL_CD><REFILLS></REFILLS><ICD9_PRI></ICD9_PRI><ICD9PRIMARYCODE2></ICD9PRIMARYCODE2><ICD9_SEC></ICD9_SEC><ICD9SECONDARYCODE2></ICD9SECONDARYCODE2><ICD10PRIMARY></ICD10PRIMARY><ICD10PRIMARYCODE2></ICD10PRIMARYCODE2><ICD10SECONDARY></ICD10SECONDARY><ICD10SECONDARYCODE2></ICD10SECONDARYCODE2><PRESCRIBER_ORDER_NO></PRESCRIBER_ORDER_NO><PA_NO></PA_NO><PRESCRIBER_ORDER_NO_CODE></PRESCRIBER_ORDER_NO_CODE><COMMENTS></COMMENTS><MAI_VER></MAI_VER><MAI_RX_DESC></MAI_RX_DESC><MAI_RX_DAYS_LATE></MAI_RX_DAYS_LATE><MAI_RX_IND></MAI_RX_IND><MAI_FILL_DESC></MAI_FILL_DESC><MAI_FILL_DAYS_LATE></MAI_FILL_DAYS_LATE><MAI_FILL_IND></MAI_FILL_IND><RX_FILL_ID></RX_FILL_ID><PRIOR_AUTH_STATUS></PRIOR_AUTH_STATUS><SRC_DESC_QUAL></SRC_DESC_QUAL><SRC_DESC></SRC_DESC><SRC_REF_NBR></SRC_REF_NBR><SRC_REF_NBR_QUAL></SRC_REF_NBR_QUAL><SRC_PHARMACY_RX_NBR></SRC_PHARMACY_RX_NBR><SRC_FILL_NBR></SRC_FILL_NBR><DRUG_USE_EVALS><DUE><REASON></REASON><PRO_SC></PRO_SC><RSLT_SC></RSLT_SC><COAGENT></COAGENT><COAGENT_CD></COAGENT_CD><CLIN_SIGNIFICANCE_CD></CLIN_SIGNIFICANCE_CD><ACK_REASON></ACK_REASON></DUE></DRUG_USE_EVALS><PROVIDER><PROVIDER_NUCC_SPECIALTY_CD></PROVIDER_NUCC_SPECIALTY_CD><LASTNAME></LASTNAME><FIRSTNAME></FIRSTNAME><PROVIDER_MID_NM></PROVIDER_MID_NM><PROVIDER_SUFFIX></PROVIDER_SUFFIX><PROVIDER_PREFIX></PROVIDER_PREFIX><PRACTICENAME></PRACTICENAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PROVIDERID></PROVIDERID><DEA></DEA><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PROVIDER><PHARMACY><NCPDP></NCPDP><PHARMACY_SPECIALTY_QUAL></PHARMACY_SPECIALTY_QUAL><PHARMACY_SPECIALTY_CD></PHARMACY_SPECIALTY_CD><PHARMACISTLASTNAME></PHARMACISTLASTNAME><PHARMACISTFIRSTNAME></PHARMACISTFIRSTNAME><NAME></NAME><ADDRESS1></ADDRESS1><ADDRESS2></ADDRESS2><CITY></CITY><STATE></STATE><ZIP></ZIP><PHONE></PHONE><FAX></FAX><EMAIL></EMAIL></PHARMACY></DRU></DRUS><UNIQUE_REQUEST>Y</UNIQUE_REQUEST><TOTAL_RECORDS>5</TOTAL_RECORDS></xml>");
        }
      
        [TestMethod]
        public void should_return_Encoded_xml_for_EligibilityResponce()
        {
            //Arrange
            string sampleXml = @"<z:row xmlns:z='#RowsetSchema' RXHUB_RESP_TIME='1.437' POC_PSWD='' RXHUB_ID='S00000000000001' AHS_ID='T00000000020132' TRANS_DATETIME='2017-09-25T14:44:08' RXHUB_UNIQUE_ID='269816617' TRANS_USAGE='T' APP_ID='NOW' IEA='' VER_RLS_CD='005010X279A1' TRANS_TYPE='271' TEST_CASE_ID='3990577815714358583' REF_ID='269816617' ACCT_ID='00000000000002454497' PAT_ID='63fb5e4c-2e22-499e-8d56-135e798f2f9d' MsgID='7e5baaa7-dd7b-4821-adaa-179dce6340a3' PartnerMsgID='269816617' INFO_SRC_NAME='Surescripts LLC' INFO_SRC_PAYER_ID='S00000000000001' INFO_SRC_DISP_NAME='' INFO_SRC_NETWORK='RXHUB' PBM_RXHUB_ID='' PRSCRBR_LAST_NM='Shakespeare' PRSCRBR_FIRST_NM='Bill' PRSCRBR_DEA_NO='VA6998566' PRSCRBR_NPI='3032140311' SITE_NAME='Shakespeare' PAYER_IDENT_CD='IL' CRD_HLDR_LAST_NM='Wiseau' CRD_HLDR_FIRST_NM='Tommy' CRD_HLDR_MID_NM='' CRD_HLDR_NM_SUFX='' PBM_FORMU_ID='' CRD_HLDR_ADDR1='' CRD_HLDR_CITY='' CRD_HLDR_STATE='' CRD_HLDR_ZIP_CD='' CRD_HLDR_DOB='' REL_CD='' PAT_LAST_NM='Wiseau' PAT_MID_NM='' PAT_FIRST_NM='Tommy' PAT_PBM_ID='' PAT_DOB='1950-07-16T00:00:00-04:00' PAT_GENDER_CD='' PAT_ZIP_CD='' ORGID='' FORMU_ID='' MAIL_ORD_NABP='' AAA_REJECT_CD='75' PAT_ADDR1='' PAT_ADDR2='' PAT_CITY='' PAT_STATE='' AAA_REJECT_CD_DESC='Subscriber/Insured Not Found (75)' PAT_NM_SUFX='' PAYER_IDENT_CD_DESC='Insured or Subscriber' CRD_HLDR_PLAN_NAME='' />";
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(sampleXml);
            XmlNode sampleXmlNode = doc.DocumentElement;

            string resultXml = @"<z:row xmlns:z='#RowsetSchema' RXHUB_RESP_TIME='1.437' POC_PSWD='' RXHUB_ID='S00000000000001' AHS_ID='T00000000020132' TRANS_DATETIME='2017-09-25T14:44:08' RXHUB_UNIQUE_ID='269816617' TRANS_USAGE='T' APP_ID='NOW' IEA='' VER_RLS_CD='005010X279A1' TRANS_TYPE='271' TEST_CASE_ID='3990577815714358583' REF_ID='269816617' ACCT_ID='00000000000002454497' PAT_ID='63fb5e4c-2e22-499e-8d56-135e798f2f9d' MsgID='7e5baaa7-dd7b-4821-adaa-179dce6340a3' PartnerMsgID='269816617' INFO_SRC_NAME='Surescripts LLC' INFO_SRC_PAYER_ID='S00000000000001' INFO_SRC_DISP_NAME='' INFO_SRC_NETWORK='RXHUB' PBM_RXHUB_ID='' PRSCRBR_LAST_NM='Shakespeare' PRSCRBR_FIRST_NM='Bill' PRSCRBR_DEA_NO='VA6998566' PRSCRBR_NPI='3032140311' SITE_NAME='Shakespeare' PAYER_IDENT_CD='IL' CRD_HLDR_LAST_NM='Wiseau' CRD_HLDR_FIRST_NM='Tommy' CRD_HLDR_MID_NM='' CRD_HLDR_NM_SUFX='' PBM_FORMU_ID='' CRD_HLDR_ADDR1='' CRD_HLDR_CITY='' CRD_HLDR_STATE='' CRD_HLDR_ZIP_CD='' CRD_HLDR_DOB='' REL_CD='' PAT_LAST_NM='Wiseau' PAT_MID_NM='' PAT_FIRST_NM='Tommy' PAT_PBM_ID='' PAT_DOB='1950-07-16T00:00:00-04:00' PAT_GENDER_CD='' PAT_ZIP_CD='' ORGID='' FORMU_ID='' MAIL_ORD_NABP='' AAA_REJECT_CD='75' PAT_ADDR1='' PAT_ADDR2='' PAT_CITY='' PAT_STATE='' AAA_REJECT_CD_DESC='Subscriber/Insured Not Found (75)' PAT_NM_SUFX='' PAYER_IDENT_CD_DESC='Insured or Subscriber' CRD_HLDR_PLAN_NAME='' />";
            XmlDocument resultDoc = new XmlDocument();
            resultDoc.LoadXml(resultXml);
            XmlNode resultNode = resultDoc.DocumentElement;

            //Act
            XmlNode result = sampleXmlNode.XmlEncode();

            //Assert
            Assert.AreEqual(result.OuterXml, resultNode.OuterXml);
        }

        [TestMethod]
        public void should_return_Encoded_xml_for_EPAResponce()
        {
            //Arrange
            string sampleXml = "<xml><data><row guidkey=\"1AA2727D - B973 - 49AB - 883F - E4228035DC1D\" acct_id=\"00000000000002454680\" select_ind=\"P\" msg=\"&lt;AllscriptsMessageEnvelope&gt;&lt;MessageDispatchHeader&gt;&lt;ID&gt;bea92756-c393-48f7-815f-751f12e29dd4&lt;/ID&gt;&lt;ClientID&gt;2454680&lt;/ClientID&gt;&lt;SamlToken /&gt;&lt;MessageType&gt;Verify&lt;/MessageType&gt;&lt;Noun&gt;ePA&lt;/Noun&gt;&lt;Verb&gt;Verified&lt;/Verb&gt;&lt;TimeStamp&gt;2020-07-24T14:26:00Z&lt;/TimeStamp&gt;&lt;Originator&gt;&lt;OriginatorName&gt;NA&lt;/OriginatorName&gt;&lt;/Originator&gt;&lt;/MessageDispatchHeader&gt;&lt;EntityContext&gt;&lt;KeyedValues&gt;&lt;KeyedValue&gt;&lt;Key&gt;AccountID&lt;/Key&gt;&lt;Value&gt;2454680&lt;/Value&gt;&lt;/KeyedValue&gt;&lt;/KeyedValues&gt;&lt;/EntityContext&gt;&lt;MessageContent&gt;&lt;PAMessage&gt;&lt;Switch&gt;&lt;TestIndicator&gt;Y&lt;/TestIndicator&gt;&lt;RecipientID&gt;2454680&lt;/RecipientID&gt;&lt;RecipientIDQualfier&gt;C&lt;/RecipientIDQualfier&gt;&lt;SenderID&gt;CoverMyMeds&lt;/SenderID&gt;&lt;SenderIDQualifier&gt;ZZZ&lt;/SenderIDQualifier&gt;&lt;SenderIdLevelThree&gt;CMM&lt;/SenderIdLevelThree&gt;&lt;AppID&gt;NCPDP-EHR&lt;/AppID&gt;&lt;AppVersion&gt;1.0&lt;/AppVersion&gt;&lt;MessageType&gt;Verify&lt;/MessageType&gt;&lt;TransactionControlNumber&gt;464712250287313784e35a0002361b14&lt;/TransactionControlNumber&gt;&lt;InitiatedTransactionControlReferenceID&gt;BA9ECF97B9CDEA11A364005056A6ED8A&lt;/InitiatedTransactionControlReferenceID&gt;&lt;SentDateTime&gt;2020-07-24T14:26:01Z&lt;/SentDateTime&gt;&lt;/Switch&gt;&lt;Status&gt;&lt;Type&gt;010&lt;/Type&gt;&lt;/Status&gt;&lt;/PAMessage&gt;&lt;/MessageContent&gt;&lt;/AllscriptsMessageEnvelope&gt;\" inserted_datetime=\"2020-07-24T10:26:01.277\" trans_type=\"VERIFY\" machine_name=\"BTS\" selected_datetime=\"2020-07-24T10:26:31.593\" inserted_datetime_utc=\"2020-07-24T14:26:01.277\" selected_datetime_utc=\"2020-07-24T14:26:31.593\" msgID=\"d8dea965-25fb-4922-8df7-ae8c80057b63  \" /></data></xml>";
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(sampleXml);
            XmlNode sampleXmlNode = doc.DocumentElement;

            string resultXml = "<xml><data><row guidkey=\"1AA2727D - B973 - 49AB - 883F - E4228035DC1D\" acct_id=\"00000000000002454680\" select_ind=\"P\" msg=\"&lt;AllscriptsMessageEnvelope&gt;&lt;MessageDispatchHeader&gt;&lt;ID&gt;bea92756-c393-48f7-815f-751f12e29dd4&lt;/ID&gt;&lt;ClientID&gt;2454680&lt;/ClientID&gt;&lt;SamlToken /&gt;&lt;MessageType&gt;Verify&lt;/MessageType&gt;&lt;Noun&gt;ePA&lt;/Noun&gt;&lt;Verb&gt;Verified&lt;/Verb&gt;&lt;TimeStamp&gt;2020-07-24T14:26:00Z&lt;/TimeStamp&gt;&lt;Originator&gt;&lt;OriginatorName&gt;NA&lt;/OriginatorName&gt;&lt;/Originator&gt;&lt;/MessageDispatchHeader&gt;&lt;EntityContext&gt;&lt;KeyedValues&gt;&lt;KeyedValue&gt;&lt;Key&gt;AccountID&lt;/Key&gt;&lt;Value&gt;2454680&lt;/Value&gt;&lt;/KeyedValue&gt;&lt;/KeyedValues&gt;&lt;/EntityContext&gt;&lt;MessageContent&gt;&lt;PAMessage&gt;&lt;Switch&gt;&lt;TestIndicator&gt;Y&lt;/TestIndicator&gt;&lt;RecipientID&gt;2454680&lt;/RecipientID&gt;&lt;RecipientIDQualfier&gt;C&lt;/RecipientIDQualfier&gt;&lt;SenderID&gt;CoverMyMeds&lt;/SenderID&gt;&lt;SenderIDQualifier&gt;ZZZ&lt;/SenderIDQualifier&gt;&lt;SenderIdLevelThree&gt;CMM&lt;/SenderIdLevelThree&gt;&lt;AppID&gt;NCPDP-EHR&lt;/AppID&gt;&lt;AppVersion&gt;1.0&lt;/AppVersion&gt;&lt;MessageType&gt;Verify&lt;/MessageType&gt;&lt;TransactionControlNumber&gt;464712250287313784e35a0002361b14&lt;/TransactionControlNumber&gt;&lt;InitiatedTransactionControlReferenceID&gt;BA9ECF97B9CDEA11A364005056A6ED8A&lt;/InitiatedTransactionControlReferenceID&gt;&lt;SentDateTime&gt;2020-07-24T14:26:01Z&lt;/SentDateTime&gt;&lt;/Switch&gt;&lt;Status&gt;&lt;Type&gt;010&lt;/Type&gt;&lt;/Status&gt;&lt;/PAMessage&gt;&lt;/MessageContent&gt;&lt;/AllscriptsMessageEnvelope&gt;\" inserted_datetime=\"2020-07-24T10:26:01.277\" trans_type=\"VERIFY\" machine_name=\"BTS\" selected_datetime=\"2020-07-24T10:26:31.593\" inserted_datetime_utc=\"2020-07-24T14:26:01.277\" selected_datetime_utc=\"2020-07-24T14:26:31.593\" msgID=\"d8dea965-25fb-4922-8df7-ae8c80057b63  \"></row></data></xml>";
            XmlDocument resultDoc = new XmlDocument();
            resultDoc.LoadXml(resultXml);
            XmlNode resultNode = resultDoc.DocumentElement;

            //Act
            XmlNode result = sampleXmlNode.XmlEncode();
            //Assert
            Assert.AreEqual(resultNode.OuterXml, result.OuterXml);
        }

        [TestMethod]
        public void should_return_Encoded_string_from_xml()
        {
            //Arrange
            string sampleXml = "<AllscriptsMessageEnvelope>n  <MessageDispatchHeader>n    <ID>89c6b0af-1fcf-4fdb-9a0d-243399fe2e67  </ID>n    <Noun>Message</Noun>n    <Verb>Received</Verb>n    <TimeStamp>2020-07-30T06:07:55</TimeStamp>n    <Description>Rx Hub Message</Description>n    <Originator>n      <OriginatorName />n    </Originator>n    <Destination>n      <SendToName />n    </Destination>n  </MessageDispatchHeader>n  <EntityContext />n  <MessageContent>n    <MessageProcessed>n      <ReplyToMessageID>8b1ea6b8-db90-4226-b89c-d0ebfd3f26f6</ReplyToMessageID>n      <TransportStatus>Success</TransportStatus>n      <ApplicationStatus>Success</ApplicationStatus>n      <Datetime>2020-07-30T06:07:55</Datetime>n      <Comment>Message Accepted by Allscripts Rx Hub.</Comment>n      <AdditionalDetails>n        <AdditionalDetail>Delivered using RxPrescriptionService WCF Service</AdditionalDetail>n      </AdditionalDetails>n    </MessageProcessed>n  </MessageContent>n</AllscriptsMessageEnvelope>";
            string EncodedFormOfSampleXml = "<AllscriptsMessageEnvelope>n  <MessageDispatchHeader>n    <ID>89c6b0af-1fcf-4fdb-9a0d-243399fe2e67  </ID>n    <Noun>Message</Noun>n    <Verb>Received</Verb>n    <TimeStamp>2020-07-30T06:07:55</TimeStamp>n    <Description>Rx Hub Message</Description>n    <Originator>n      <OriginatorName></OriginatorName>n    </Originator>n    <Destination>n      <SendToName></SendToName>n    </Destination>n  </MessageDispatchHeader>n  <EntityContext></EntityContext>n  <MessageContent>n    <MessageProcessed>n      <ReplyToMessageID>8b1ea6b8-db90-4226-b89c-d0ebfd3f26f6</ReplyToMessageID>n      <TransportStatus>Success</TransportStatus>n      <ApplicationStatus>Success</ApplicationStatus>n      <Datetime>2020-07-30T06:07:55</Datetime>n      <Comment>Message Accepted by Allscripts Rx Hub.</Comment>n      <AdditionalDetails>n        <AdditionalDetail>Delivered using RxPrescriptionService WCF Service</AdditionalDetail>n      </AdditionalDetails>n    </MessageProcessed>n  </MessageContent>n</AllscriptsMessageEnvelope>";

            //Act
            string result = sampleXml.XmlEncode();

            //Assert
            Assert.AreEqual(result, EncodedFormOfSampleXml);
        }

        [TestMethod]
        public void should_return_encoded_ack_string()
        {
            //Arrange
            string sampleXml = "<ack></ack>";

            //Act
            string result = sampleXml.XmlEncode();

            //Assert
            Assert.AreEqual(result, sampleXml);
        }

        [TestMethod]
        public void should_return_emptyString_for_null()
        {
            //Arrange
            string sampleXml = null;

            //Act
            string result = sampleXml.XmlEncode();

            //Assert
            Assert.AreEqual(result, "");
        }

        [TestMethod]
        public void should_return_sameString_if_exception()
        {
            string sampleXml = "<a>&copy;</a>";
            //Act
            string result = sampleXml.XmlEncode();

            //Assert
            Assert.AreEqual(result, sampleXml);
        }

        [TestMethod]
        public void should_return_same_value_after_valiating_Nested_Json()
        {
            string parameterValue = @"{'name':'Ram','age':'27','med':{'m1':'t1','m2':'t2','m3':'t3'},'Type':'100'}";
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result.Replace('"', '\''), parameterValue);
        }

        [TestMethod]

        public void should_return_same_value_after_valiating_Json()
        {
            string parameterValue = @"{'name':'Ram','age':'27','med':{'m1':'t1','m2':'t2','m3':'t3'}}";
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result.Replace('"', '\''), parameterValue);
        }

        [TestMethod]
        public void should_return_null_if_the_value_is_null()
        {
            string parameterValue = null;
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result, parameterValue);
        }

        [TestMethod]
        public void should_return_empty_if_the_value_is_empty()
        {
            string parameterValue = string.Empty;
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result, parameterValue);
        }

        [TestMethod]
        public void should_return_same_value_if_the_parse_fails()
        {
            string parameterValue = "85DDE3C3-F30D-48B7-BB94-3552FE0D6129";
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result.Trim('"'), parameterValue);
        }

        [TestMethod]
        public void should_return_null_or_empty_if_the_value_is_null_or_empty()
        {
            string parameterValue = @"{'PatientId':'','PatientName':null,'MessageVisibility':'false','MessageIcon':null,'MessageTooltip':null,'MessageText':null}";
            string result = parameterValue.ToJsonEncode();
            Assert.AreEqual(result.Replace('"', '\''), parameterValue);
        }

        [TestMethod]
        public void should_return_same_value_after_validating_query_string_with_single_sub_params()
        {
            string queryParam = "EditUser?status=noLic";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_after_validating_query_string_with_multiple_sub_params() {         
            string queryParam = "EditUser?status=noLic&From=SelectPatient";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_after_validating_query_string_with_multiple_params()
        {
            string queryParam = "EditUser?status=noLic?From=SelectPatient/12";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_after_validating_query_string_with_encrypted_chars()
        {
            string queryParam = "SelectPatient%27-alert(document.domain)-%27";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_for_a_made_up_string()
        {
            string queryParam = "abc?=?asas=";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_for_another_made_up_string()
        {
            string queryParam = "abc=&asas";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_for_a_256_char_long_string()
        {
            string queryParam = "EditUsers.aspx/ThisIsSupposedToGoToAnotherPageButI%WAS%ASKED%TO%MAKE%A%256%CHARACTERS%LONG%URLTHATCONTAINSOTHERSPECIALCHARACTERSASWELLTOHandleBigLengthUrlParsingAndIFeelThatTHISISGoingonprettysmoothtillnow?-somyurlhereisinmyheadaboutthelengthof256charsnow";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual(queryParam, result);
        }

        [TestMethod]
        public void should_return_same_value_for_a_XSS_char_long_string()
        {
            string queryParam = "EditUsers.aspx<script></script>";
            string result = queryParam.ToQueryStringEncode();
            Assert.AreEqual("EditUsers.aspx&lt;script&gt;&lt;/script&gt;", result);
        }
    }
}


    

