
using System;

namespace eRxWeb.AppCode.Authorize
{
    [Flags]
    public enum UserCategory
    {
        GENERAL_USER = 1,
        PROVIDER = 2,
        POB_LIMITED = 4,
        POB_REGULAR = 8,
        PHYSICIAN_ASSISTANT = 16,
        PHYSICIAN_ASSISTANT_SUPERVISED = 32,
        POB_SUPER = 64,

        NONE = 128,//Means no role.Just authenticated user

        PRESCRIBER = PROVIDER | PHYSICIAN_ASSISTANT | PHYSICIAN_ASSISTANT_SUPERVISED,
        All = GENERAL_USER | PROVIDER | POB_LIMITED | POB_REGULAR | PHYSICIAN_ASSISTANT | PHYSICIAN_ASSISTANT_SUPERVISED | POB_SUPER,
        PRESCRIBER_OR_POB = PROVIDER | POB_LIMITED | POB_REGULAR | PHYSICIAN_ASSISTANT | PHYSICIAN_ASSISTANT_SUPERVISED | POB_SUPER,
        PA_SUP_AND_POBs = POB_LIMITED | POB_REGULAR | PHYSICIAN_ASSISTANT_SUPERVISED | POB_SUPER,
        POB = POB_LIMITED | POB_REGULAR | POB_SUPER,
        EXCEPT_GENERAL_USER_AND_POB_LIMITED = PROVIDER | POB_REGULAR | PHYSICIAN_ASSISTANT | PHYSICIAN_ASSISTANT_SUPERVISED | POB_SUPER
    }

    [Flags]
    public enum UserPrivilege
    {
        ANY = 1,
        ADMIN = 2
    }
}